### PR TITLE
Development

### PR DESCRIPTION
**Pull request by s-ashwinkumar**

### CODE REVIEW

**Comment by dtsdwarak** [comment]
@s-ashwinkumar : Can you also push the latest DB dump into the repo? Also, what about trying this out at Heroku? I guess it supports git hooks to sync the live app with the latest updates?

**Comment by s-ashwinkumar** [comment]
Hey, we never got this up and running @Lister :P ...This i just wanted to fork and revamp it for something else...so i merged dev into master and forked it.

**Comment by hameedfiaz** [comment]
Oh I see 😜 awesome!!!

**Comment by dtsdwarak** [comment]
Oh, okay :+1:

**Comment by s-ashwinkumar** [comment]
@dwarak-lister  vera eda ideas irunda sollu da :D panalam ;)

**Comment by dtsdwarak** [comment]
@s-ashwinkumar Indha project ke solreengala illa general ah va?

**Comment by s-ashwinkumar** [comment]
@dtsdwarak general da :) :+1:

**Comment by dtsdwarak** [comment]
@s-ashwinkumar Thinking of doing Local LAN Audio streamer. You add a folder to sync and it must be accessible to all devices in the same LAN via web-frontend. This can also be made accessible via DLNA protocol. Very basic idea is this.

**Pull request merged**
